---
- name: Install JDK
  zypper:
    name: "{{ jdk_package }}"
  when: "{{ install_jdk }}"

- name: Import Confluent Repository Public Key
  rpm_key:
    state: present
    key: "{{ schema_registry_rpm_repo_key }}"
  when: "{{ install_from_confluent }}"

- name: Add Confluent Repository
  zypper_repository:
    state: present
    name: "Confluent Package Mirror"
    repo: "{{ schema_registry_rpm_repo }}"
  when: "{{ install_from_confluent }}"

- name: Add Custom Confluent Repository
  zypper_repository:
    state: present
    name: "Confluent Package Mirror"
    repo: "{{ schema_registry_rpm_repo }}"
  when:  "not {{ install_from_confluent }}"

- name: Install Schema Registry
  zypper:
    state: present
    name: "{{ schema_registry_rpm }}"
